### ISSUE TITLE
Feature Request - Share Webpage from Browser to Create New Bookmark Entry

### ISSUE THREAD

**Issue by cosmobooker** [aerocyber/osmata#36]
This is just a suggestion to add the ability to share a webpage in your browser to this app and have it auto-fill the *Add Record* form, allowing you to save the webpage as a bookmark.

**Comment by aerocyber** [comment]
Thanks for the suggestion! This feature was planned for a while but I have no technical knowledge to implement it. Hence is being put off for a while. I'll be glad if you can help with this one.

**Comment by aerocyber** [comment]
So the approach I am thinking for adding this feature is to implement a URL resolver which could open Sitemarker with the record name as the title of the tab and the url the current url.

Tl;dr: Add the resolver in front of the URL to get Sitemarker's add records up with values autofilled. All yet to be done after that is to confirm adding the record. 

This feature may take a while to be implemented properly but please do look forward to it!

**Comment by aerocyber** [comment]
Hey @cosmobooker! Thanks for reporting the issues and patiently waiting for them to be implemented. Since you have opened 3 issues, I will summarize the status here to avoid multiple pings:

- This issue: This is now solved. You can now share bookmarks from Android to the app by using the share menu option. As soon as possible, a build of the app supporting this feature will be made available. Please do let me know if it does not work.
- Issue #34: Sitemarker 3 doesn't support import/export yet. However, it will be made available in version 3.1.0. I did not have enough time to test the input and output files so the fix for this issue did not make it into 3.0. However, I want you to know that the fix is ready and will be available in the next release.
- Issue #35: As with the above issue, I am not confident in the fix I had made for this issue as well and hence did not include it in this release. I will include the fix for this issue in the next release along with the previous issue.

I appreciate you reporting multiple issues and feature requests for Sitemarker. Thank you!
